services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    container_name: asiayo-laravel
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    container_name: asiayo-nginx
  mysql:
    image: mysql:lts
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: asiayo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: asiayo-mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 30


      # docker exec -it asiayo-laravel php artisan migrate
